version: "3.9"

services:
  web:
    image: odoo:19
    depends_on:
      - db
    ports:
      - "8075:8069"
    volumes:
      - ./volumesOdoo/addons:/mnt/extra-addons
    user: root
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    volumes:
      - ./volumesOdoo/dataPostgreSQL:/var/lib/postgresql/data
